### PR TITLE
Ell lib

### PR DESCRIPTION
**Pull request by hjunkes**

### CODE REVIEW

**Comment by anjohnson** [comment]
NB: This branch also contains #7, #8 and #9; merge those PRs first.

**Comment by hjunkes** [comment]
Ok, made a mistake. Will fix it

FHI, Heinz Junkes

**Comment by anjohnson** [comment]
@hjunkes You don't need to fix it, if I do the merges in the same order nobody will notice, and I really don't need you to spend more time on this – thanks anyway!

**Comment by anjohnson** [comment]
Merged by hand

**Pull request closed without merging**
