### PR TITLE
Update postfix.h with doxygen annotations

### PR DESCRIPTION
**Pull request by hjunkes**
The first attempt to document a header file with doxygen

### CODE REVIEW

**Comment by ronaldomercado** [comment]
Hi.
What is the idea behind using @defgroup ?
It looks interesting and I am wondering if it should be used in other pull requests.
Thanks,
Ronaldo

**Comment by ronaldomercado** [comment]
@anjohnson , can you comment on the use of @defgroup?
Thanks,
Ronaldo

**Comment by hjunkes** [comment]
Hi Ronaldo,

I am working on bucketLib.
Just doing this:

/**
  * @defgroup bucketLibDefs bucketLib Macros
  * @{
  */
  /**
   * @def BUCKET_SUCCESS
   * @brief defined to S_bucket_success (0)
   */

#define BUCKET_SUCCESS          S_bucket_success
  /**
   * @def S_bucket_success
   * @brief defined as 0
   */
#define S_bucket_success        0
  /**
   * @def S_bucket_noMemory
   * @brief Memory allocation failed
   */

#define S_bucket_noMemory       (M_bucket | 1)
  /**
   * @def S_bucket_idInUse
   * @brief Identifier already in use
   */
#define S_bucket_idInUse        (M_bucket | 2)
  /**
   * @def S_bucket_uknId
   * @brief Unknown identifier
   */
#define S_bucket_uknId          (M_bucket | 3)
/** @} */

This gives this output:

Heinz

**Comment by ronaldomercado** [comment]
Thanks for the comment. I could not see the output that you refer to.
I have found that the defgroup creates an entry under the 'Modules' header of the doxygen generated pages and it seems useful.
Regards,
Ronaldo

**Pull request merged**
